/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jKoNqQf9yT8Pn9RBFtbwnS
// Component: gNhkYRmNfkLa

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeaderNav from "../../HeaderNav"; // plasmic-import: my-sNiLoLdMm/component
import Footer from "../../Footer"; // plasmic-import: 53qTPHRQ24MF/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectcss
import sty from "./PlasmicTeam.module.css"; // plasmic-import: gNhkYRmNfkLa/css

import LinkedinSvgrepoComSvgIcon from "./icons/PlasmicIcon__LinkedinSvgrepoComSvg"; // plasmic-import: ZZu2QufwXikE/icon

createPlasmicElementProxy;

export type PlasmicTeam__VariantMembers = {};
export type PlasmicTeam__VariantsArgs = {};
type VariantPropType = keyof PlasmicTeam__VariantsArgs;
export const PlasmicTeam__VariantProps = new Array<VariantPropType>();

export type PlasmicTeam__ArgsType = {};
type ArgPropType = keyof PlasmicTeam__ArgsType;
export const PlasmicTeam__ArgProps = new Array<ArgPropType>();

export type PlasmicTeam__OverridesType = {
  root?: Flex__<"div">;
  headerNav?: Flex__<typeof HeaderNav>;
  section?: Flex__<"section">;
  ourBoardOfAdvisors?: Flex__<"div">;
  ourBoardOfAdvisors2?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultTeamProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTeam__RenderFunc(props: {
  variants: PlasmicTeam__VariantsArgs;
  args: PlasmicTeam__ArgsType;
  overrides: PlasmicTeam__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <HeaderNav
            data-plasmic-name={"headerNav"}
            data-plasmic-override={overrides.headerNav}
            className={classNames("__wab_instance", sty.headerNav)}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__bDpda)}>
              <div className={classNames(projectcss.all, sty.freeBox__fKpY)}>
                <div
                  data-plasmic-name={"ourBoardOfAdvisors"}
                  data-plasmic-override={overrides.ourBoardOfAdvisors}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.ourBoardOfAdvisors
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Board of Directors"}
                    </span>
                  </React.Fragment>
                </div>
                <div className={classNames(projectcss.all, sty.columns__jjG7K)}>
                  <div
                    className={classNames(projectcss.all, sty.column__rKHxg)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__xjHX)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/_1746575659001Jpeg.jpg",
                        fullWidth: 800,
                        fullHeight: 800,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__b6HUk
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__i8RC4
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Ferananda Ibarra"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mo12A
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__tL80W
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FFFFFF" }}
                              >
                                {"Secretary"}
                              </span>
                            </React.Fragment>
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jWs5S
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__xzTuz
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-G_UhQWFsj2RA)" }}
                              >
                                {
                                  "Designing Societal Systems for Interdependence. Financial and economies that serve life, bioregional work & community aliveness (culture). "
                                }
                              </span>
                            </React.Fragment>
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___0VjT2
                      )}
                      component={Link}
                      href={"https://www.linkedin.com/in/ferananda/"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__roUc2)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__oeHvc)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__s5DhR)}
                      displayHeight={"206px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/headshot2Jpg.jpg",
                        fullWidth: 2500,
                        fullHeight: 1894,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__z1MXf
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__b9YE
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Arthur Brock"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e2Zwe
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__eQaiP
                            )}
                          >
                            {"President "}
                          </h5>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sapN
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__rWjx0
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-G_UhQWFsj2RA)" }}
                              >
                                {
                                  "A systems architect and technology innovator with more than two decades of experience building decentralized economic systems."
                                }
                              </span>
                            </React.Fragment>
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__n4TQk
                      )}
                      component={Link}
                      href={"https://www.linkedin.com/in/artbrock/"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__yYdJr)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___42Yp)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__l4ZmH)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/_1759773825168Jpeg.jpg",
                        fullWidth: 200,
                        fullHeight: 200,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vt5XN
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__kuLji
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Ishan Shapiro"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__g7HgT
                      )}
                    >
                      {"Chief Financial Officer"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wkNse
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__qfR6R
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FFFFFF" }}
                              >
                                {
                                  "An innovative creative director with over 15 years of experience spearheading groundbreaking immersive storytelling and experience design for a wide range of global brands"
                                }
                              </span>
                            </React.Fragment>
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__ok30Y
                      )}
                      component={Link}
                      href={"https://www.linkedin.com/in/1shan/"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__ppM0)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__d47Np)}>
                <div
                  data-plasmic-name={"ourBoardOfAdvisors2"}
                  data-plasmic-override={overrides.ourBoardOfAdvisors2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.ourBoardOfAdvisors2
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Advisory Committee"}
                    </span>
                  </React.Fragment>
                </div>
                <div className={classNames(projectcss.all, sty.columns__hpFso)}>
                  <div
                    className={classNames(projectcss.all, sty.column__bSai7)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__slLy)}
                      displayHeight={"207px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"208px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/image5.webp",
                        fullWidth: 736,
                        fullHeight: 552,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__c403V
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__y7Bbi
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Peta Milan"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Kgyq
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__oLzNa
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FFFFFF" }}
                              >
                                {
                                  "Foundational thinker on Regenerative Investing, and is Principal of Henmil Group Family Office in Dubai."
                                }
                              </span>
                            </React.Fragment>
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__gLvhe
                      )}
                      component={Link}
                      href={
                        "https://www.linkedin.com/in/peta-milan-she-her-b4307a27/"
                      }
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg___5JAjR)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__b55W7)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__nmsEp)}
                      displayHeight={"194px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/courneyMurthaJpeg.jpg",
                        fullWidth: 200,
                        fullHeight: 200,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ekHpw
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__l6Y38
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Courtney Murtha"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5VUfH
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__tlob1
                            )}
                          >
                            {
                              "Strategist and financial innovator bridging institutional markets with the emerging regenerative economy."
                            }
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__sU91G
                      )}
                      component={Link}
                      href={
                        "https://www.linkedin.com/in/courtney-murtha-012a052b/"
                      }
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__dCQ7)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                  <div className={classNames(projectcss.all, sty.column__z56N)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mfWBq)}
                      displayHeight={"202px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/hhsReducedSizeHeadshotJpeg.jpg",
                        fullWidth: 432,
                        fullHeight: 455,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__g0G0
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__wJuni
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Helen Holden"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dkdJn
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__nL0Qf
                            )}
                          >
                            {
                              "Legal strategist and transformational systems, brings deep insight into legal, social, and financial systems."
                            }
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__yrupP
                      )}
                      component={Link}
                      href={"https://www.linkedin.com/in/helenslottje/"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__rD9Jc)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                  <div className={classNames(projectcss.all, sty.column__hATg)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qShvE)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/kateBennettJpeg.jpg",
                        fullWidth: 200,
                        fullHeight: 200,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yLbNf
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__aEbS
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#E5E7EB" }}
                              >
                                {"Kate Bennett"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ugqn
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6___9U4VQ
                            )}
                          >
                            {
                              "Systems innovator reimagining how capital flows can serve life by default, not exception."
                            }
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__xiVu9
                      )}
                      component={Link}
                      href={"https://www.linkedin.com/in/ktlbennett/"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__a1Zmd)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.columns__yqmUw)}>
                  <div
                    className={classNames(projectcss.all, sty.column___7TRf0)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___7DWk8)}
                      displayHeight={"207px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"208px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/leeWhite937X1024Jpg.jpg",
                        fullWidth: 937,
                        fullHeight: 1024,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d8Rj
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__vCFa
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Lee White"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__va4Bt
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__dYzdm
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FFFFFF" }}
                              >
                                {
                                  "Lee is a creative catalyst urging along the development of social impact technologies."
                                }
                              </span>
                            </React.Fragment>
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__jTvfQ
                      )}
                      component={Link}
                      href={
                        "https://www.linkedin.com/in/lee-white-live-in-flow/"
                      }
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg___4Pcmq)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                  <div className={classNames(projectcss.all, sty.column__eiXu)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yRyOk)}
                      displayHeight={"194px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/courneyMurthaJpeg.jpg",
                        fullWidth: 200,
                        fullHeight: 200,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cLqfe
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__jOeOb
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Courtney Murtha"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jP2Oi
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__eWinC
                            )}
                          >
                            {
                              "Strategist and financial innovator bridging institutional markets with the emerging regenerative economy."
                            }
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__lvSdN
                      )}
                      component={Link}
                      href={
                        "https://www.linkedin.com/in/courtney-murtha-012a052b/"
                      }
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__cilp6)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__bjUBj)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__pDiwT)}
                      displayHeight={"202px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/hhsReducedSizeHeadshotJpeg.jpg",
                        fullWidth: 432,
                        fullHeight: 455,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rQ2Z6
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__zOmk3
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-HIt_SMre_dXW)" }}
                              >
                                {"Helen Holden Slottje"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ns4Nu
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__c0TuV
                            )}
                          >
                            {
                              "Legal strategist and transformational systems, brings deep insight into legal, social, and financial systems."
                            }
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__fOmIr
                      )}
                      component={Link}
                      href={"https://www.linkedin.com/in/helenslottje/"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__lLEn
                        )}
                        component={Link}
                        platform={"nextjs"}
                      >
                        <LinkedinSvgrepoComSvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___0B5PM
                          )}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </PlasmicLink__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__jc1Pj)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___48SK)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/kateBennettJpeg.jpg",
                        fullWidth: 200,
                        fullHeight: 200,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__c4ZYo
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__mao4I
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#E5E7EB" }}
                              >
                                {"Kate Bennett"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kId3S
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__bsGAx
                            )}
                          >
                            {
                              "Systems innovator reimagining how capital flows can serve life by default, not exception."
                            }
                          </h6>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__v0ToY
                      )}
                      component={Link}
                      href={"https://www.linkedin.com/in/ktlbennett/"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <LinkedinSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__g288)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerNav",
    "section",
    "ourBoardOfAdvisors",
    "ourBoardOfAdvisors2",
    "footer"
  ],
  headerNav: ["headerNav"],
  section: ["section", "ourBoardOfAdvisors", "ourBoardOfAdvisors2"],
  ourBoardOfAdvisors: ["ourBoardOfAdvisors"],
  ourBoardOfAdvisors2: ["ourBoardOfAdvisors2"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerNav: typeof HeaderNav;
  section: "section";
  ourBoardOfAdvisors: "div";
  ourBoardOfAdvisors2: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTeam__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTeam__VariantsArgs;
    args?: PlasmicTeam__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTeam__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTeam__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTeam__ArgProps,
          internalVariantPropNames: PlasmicTeam__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTeam__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTeam";
  } else {
    func.displayName = `PlasmicTeam.${nodeName}`;
  }
  return func;
}

export const PlasmicTeam = Object.assign(
  // Top-level PlasmicTeam renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerNav: makeNodeComponent("headerNav"),
    section: makeNodeComponent("section"),
    ourBoardOfAdvisors: makeNodeComponent("ourBoardOfAdvisors"),
    ourBoardOfAdvisors2: makeNodeComponent("ourBoardOfAdvisors2"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicTeam
    internalVariantProps: PlasmicTeam__VariantProps,
    internalArgProps: PlasmicTeam__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTeam;
/* prettier-ignore-end */
