/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jKoNqQf9yT8Pn9RBFtbwnS

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsdpo10UMbgXc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: DPO10U_MbgXC/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsdpo10UMbgXc
});
