/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jKoNqQf9yT8Pn9RBFtbwnS
// Component: GlJxAz5y_WB7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeaderNav from "../../HeaderNav"; // plasmic-import: my-sNiLoLdMm/component
import Footer from "../../Footer"; // plasmic-import: 53qTPHRQ24MF/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectcss
import sty from "./PlasmicAbout.module.css"; // plasmic-import: GlJxAz5y_WB7/css

createPlasmicElementProxy;

export type PlasmicAbout__VariantMembers = {};
export type PlasmicAbout__VariantsArgs = {};
type VariantPropType = keyof PlasmicAbout__VariantsArgs;
export const PlasmicAbout__VariantProps = new Array<VariantPropType>();

export type PlasmicAbout__ArgsType = {};
type ArgPropType = keyof PlasmicAbout__ArgsType;
export const PlasmicAbout__ArgProps = new Array<ArgPropType>();

export type PlasmicAbout__OverridesType = {
  root?: Flex__<"div">;
  headerNav?: Flex__<typeof HeaderNav>;
  img?: Flex__<typeof PlasmicImg__>;
  qualification2?: Flex__<"div">;
  administration?: Flex__<"div">;
  compliance?: Flex__<"div">;
  qualification3?: Flex__<"div">;
  administration2?: Flex__<"div">;
  compliance2?: Flex__<"div">;
  qualification4?: Flex__<"div">;
  administration3?: Flex__<"div">;
  compliance3?: Flex__<"div">;
  qualification5?: Flex__<"div">;
  administration4?: Flex__<"div">;
  administration5?: Flex__<"div">;
  qualification6?: Flex__<"div">;
  administration6?: Flex__<"div">;
  compliance4?: Flex__<"div">;
  qualification7?: Flex__<"div">;
  administration7?: Flex__<"div">;
  administration8?: Flex__<"div">;
  qualification8?: Flex__<"div">;
  administration9?: Flex__<"div">;
  compliance5?: Flex__<"div">;
  qualification9?: Flex__<"div">;
  administration10?: Flex__<"div">;
  administration11?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultAboutProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAbout__RenderFunc(props: {
  variants: PlasmicAbout__VariantsArgs;
  args: PlasmicAbout__ArgsType;
  overrides: PlasmicAbout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicAbout.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAbout.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAbout.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicAbout.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicAbout.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicAbout.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <section className={classNames(projectcss.all, sty.section__dg25M)}>
            <HeaderNav
              data-plasmic-name={"headerNav"}
              data-plasmic-override={overrides.headerNav}
              className={classNames("__wab_instance", sty.headerNav)}
            />
          </section>
          <section className={classNames(projectcss.all, sty.section__fswAz)}>
            <div className={classNames(projectcss.all, sty.freeBox__fQvjl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iuWeN
                )}
              >
                {
                  "Real Assets foundation technical arm -\nThe Real Assets Registry "
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__m8CeH
                )}
              >
                {
                  "It will build the Real Assets Registry & Management App, designed to provide title owners with direct access to their unitized assets."
                }
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__eu35E)}>
            <div className={classNames(projectcss.all, sty.freeBox__kp1Yg)}>
              <div className={classNames(projectcss.all, sty.freeBox__buTu7)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mGKap
                  )}
                >
                  {"What is the real asset registry?"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o6Yuw
                  )}
                >
                  {
                    "The Real Assets Registry serves as the backbone of the Real Assets Ecosystem.\n\nThe Digital backbone of a regenerative place-based asset class.\n\n It is a decentralized ledger built on Holochain for registering, unitizing, managing, and tracking the lifecycle of mineral rights and mineral-backed real estate. It enables asset holders to unlock economic value from in-ground resources by converting large mineral holdings into unitized titles, opening access to both real estate (1031 exchange) and cryptocurrency markets. The Registry ensures traceability, legal compliance, and transparency in every asset's journey from registration to market, preventing double spending and ensuring compliance with regenerative land management goals."
                  }
                </div>
              </div>
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"365px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"326px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/realassets_foundation_homepage/images/image4.png",
                  fullWidth: 1080,
                  fullHeight: 1350,
                  aspectRatio: undefined
                }}
              />
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__a4T)}>
            <div className={classNames(projectcss.all, sty.freeBox__cYxq)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dNvDf
                )}
              >
                {"Through the Real Assets Registry, the Foundation:"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__of51M
                )}
              >
                {
                  "1) Tracks mineral, biological, and social estates.\n2) Unitizes verified resources into tradable, compliant real-estate units.\n3) Oversees long-term release schedules that balance market stability with planetary regeneration."
                }
              </div>
            </div>
            <section className={classNames(projectcss.all, sty.section__bUukl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zYuo3
                )}
              >
                {"Core Functions"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__pmXnT)}>
                <div
                  data-plasmic-name={"qualification2"}
                  data-plasmic-override={overrides.qualification2}
                  className={classNames(projectcss.all, sty.qualification2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__o8Lmt
                    )}
                  >
                    {"Asset Registration \nand Unitization:"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"administration"}
                  data-plasmic-override={overrides.administration}
                  className={classNames(projectcss.all, sty.administration)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__m4Jvk)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uMnCt
                      )}
                    >
                      {"Market Integration:"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"compliance"}
                  data-plasmic-override={overrides.compliance}
                  className={classNames(projectcss.all, sty.compliance)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hcHko)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fVuvW
                      )}
                    >
                      {"Lifecycle \nManagement:"}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___4E3Bh)}>
                <div
                  data-plasmic-name={"qualification3"}
                  data-plasmic-override={overrides.qualification3}
                  className={classNames(projectcss.all, sty.qualification3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uIuM9
                    )}
                  >
                    {"Regenerative \nCompliance:"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"administration2"}
                  data-plasmic-override={overrides.administration2}
                  className={classNames(projectcss.all, sty.administration2)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__s0L8L)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nsdgj
                      )}
                    >
                      {"Administration"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"compliance2"}
                  data-plasmic-override={overrides.compliance2}
                  className={classNames(projectcss.all, sty.compliance2)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tfyPo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qU5VP
                      )}
                    >
                      {"Compliance"}
                    </div>
                  </div>
                </div>
              </div>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__hOcEk)}>
                  <div
                    data-plasmic-name={"qualification4"}
                    data-plasmic-override={overrides.qualification4}
                    className={classNames(projectcss.all, sty.qualification4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__po44D
                      )}
                    >
                      {"Asset Registration \nand Unitization:"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration3"}
                    data-plasmic-override={overrides.administration3}
                    className={classNames(projectcss.all, sty.administration3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__c1T2S)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__o1Vfc
                        )}
                      >
                        {"Market Integration:"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"compliance3"}
                    data-plasmic-override={overrides.compliance3}
                    className={classNames(projectcss.all, sty.compliance3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vfVkl)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vc5Iu
                        )}
                      >
                        {"Lifecycle \nManagement:"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"qualification5"}
                    data-plasmic-override={overrides.qualification5}
                    className={classNames(projectcss.all, sty.qualification5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nsv21
                      )}
                    >
                      {"Asset Registration \nand Unitization:"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration4"}
                    data-plasmic-override={overrides.administration4}
                    className={classNames(projectcss.all, sty.administration4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qcciP)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uLmE7
                        )}
                      >
                        {"Asset Registration"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration5"}
                    data-plasmic-override={overrides.administration5}
                    className={classNames(projectcss.all, sty.administration5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1FLk5
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__j72Gy
                        )}
                      >
                        {"Market Integration:"}
                      </div>
                    </div>
                  </div>
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox___6OxTq)}
                >
                  <div
                    data-plasmic-name={"qualification6"}
                    data-plasmic-override={overrides.qualification6}
                    className={classNames(projectcss.all, sty.qualification6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uTgRp
                      )}
                    >
                      {"Asset Registration \nand Unitization:"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration6"}
                    data-plasmic-override={overrides.administration6}
                    className={classNames(projectcss.all, sty.administration6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__c23D8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zlQaL
                        )}
                      >
                        {"Market Integration:"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"compliance4"}
                    data-plasmic-override={overrides.compliance4}
                    className={classNames(projectcss.all, sty.compliance4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lllaP)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k45C
                        )}
                      >
                        {"Lifecycle \nManagement:"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"qualification7"}
                    data-plasmic-override={overrides.qualification7}
                    className={classNames(projectcss.all, sty.qualification7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mhh4R
                      )}
                    >
                      {"Asset Registration \nand Unitization:"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration7"}
                    data-plasmic-override={overrides.administration7}
                    className={classNames(projectcss.all, sty.administration7)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lsNlZ)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fueSa
                        )}
                      >
                        {"Lifecycle Management"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration8"}
                    data-plasmic-override={overrides.administration8}
                    className={classNames(projectcss.all, sty.administration8)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hymOw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__p9B4K
                        )}
                      >
                        {"Regenerative Compliance"}
                      </div>
                    </div>
                  </div>
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__hWmhm)}>
                  <div
                    data-plasmic-name={"qualification8"}
                    data-plasmic-override={overrides.qualification8}
                    className={classNames(projectcss.all, sty.qualification8)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3K8Sh
                      )}
                    >
                      {"Asset Registration \nand Unitization:"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration9"}
                    data-plasmic-override={overrides.administration9}
                    className={classNames(projectcss.all, sty.administration9)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hEHw0)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9JDK
                        )}
                      >
                        {"Market Integration:"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"compliance5"}
                    data-plasmic-override={overrides.compliance5}
                    className={classNames(projectcss.all, sty.compliance5)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hq7T9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wQtNd
                        )}
                      >
                        {"Lifecycle \nManagement:"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"qualification9"}
                    data-plasmic-override={overrides.qualification9}
                    className={classNames(projectcss.all, sty.qualification9)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dcYGx
                      )}
                    >
                      {"Asset Registration \nand Unitization:"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration10"}
                    data-plasmic-override={overrides.administration10}
                    className={classNames(projectcss.all, sty.administration10)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__iqlo9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vn8Ja
                        )}
                      >
                        {"Administration & Compliance"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"administration11"}
                    data-plasmic-override={overrides.administration11}
                    className={classNames(projectcss.all, sty.administration11)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1PrTm
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xxgk3
                        )}
                      >
                        {"Asset Unitization"}
                      </div>
                    </div>
                  </div>
                </div>
              ) : null}
            </section>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerNav",
    "img",
    "qualification2",
    "administration",
    "compliance",
    "qualification3",
    "administration2",
    "compliance2",
    "qualification4",
    "administration3",
    "compliance3",
    "qualification5",
    "administration4",
    "administration5",
    "qualification6",
    "administration6",
    "compliance4",
    "qualification7",
    "administration7",
    "administration8",
    "qualification8",
    "administration9",
    "compliance5",
    "qualification9",
    "administration10",
    "administration11",
    "footer"
  ],
  headerNav: ["headerNav"],
  img: ["img"],
  qualification2: ["qualification2"],
  administration: ["administration"],
  compliance: ["compliance"],
  qualification3: ["qualification3"],
  administration2: ["administration2"],
  compliance2: ["compliance2"],
  qualification4: ["qualification4"],
  administration3: ["administration3"],
  compliance3: ["compliance3"],
  qualification5: ["qualification5"],
  administration4: ["administration4"],
  administration5: ["administration5"],
  qualification6: ["qualification6"],
  administration6: ["administration6"],
  compliance4: ["compliance4"],
  qualification7: ["qualification7"],
  administration7: ["administration7"],
  administration8: ["administration8"],
  qualification8: ["qualification8"],
  administration9: ["administration9"],
  compliance5: ["compliance5"],
  qualification9: ["qualification9"],
  administration10: ["administration10"],
  administration11: ["administration11"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerNav: typeof HeaderNav;
  img: typeof PlasmicImg__;
  qualification2: "div";
  administration: "div";
  compliance: "div";
  qualification3: "div";
  administration2: "div";
  compliance2: "div";
  qualification4: "div";
  administration3: "div";
  compliance3: "div";
  qualification5: "div";
  administration4: "div";
  administration5: "div";
  qualification6: "div";
  administration6: "div";
  compliance4: "div";
  qualification7: "div";
  administration7: "div";
  administration8: "div";
  qualification8: "div";
  administration9: "div";
  compliance5: "div";
  qualification9: "div";
  administration10: "div";
  administration11: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAbout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAbout__VariantsArgs;
    args?: PlasmicAbout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAbout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAbout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAbout__ArgProps,
          internalVariantPropNames: PlasmicAbout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAbout";
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`;
  }
  return func;
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerNav: makeNodeComponent("headerNav"),
    img: makeNodeComponent("img"),
    qualification2: makeNodeComponent("qualification2"),
    administration: makeNodeComponent("administration"),
    compliance: makeNodeComponent("compliance"),
    qualification3: makeNodeComponent("qualification3"),
    administration2: makeNodeComponent("administration2"),
    compliance2: makeNodeComponent("compliance2"),
    qualification4: makeNodeComponent("qualification4"),
    administration3: makeNodeComponent("administration3"),
    compliance3: makeNodeComponent("compliance3"),
    qualification5: makeNodeComponent("qualification5"),
    administration4: makeNodeComponent("administration4"),
    administration5: makeNodeComponent("administration5"),
    qualification6: makeNodeComponent("qualification6"),
    administration6: makeNodeComponent("administration6"),
    compliance4: makeNodeComponent("compliance4"),
    qualification7: makeNodeComponent("qualification7"),
    administration7: makeNodeComponent("administration7"),
    administration8: makeNodeComponent("administration8"),
    qualification8: makeNodeComponent("qualification8"),
    administration9: makeNodeComponent("administration9"),
    compliance5: makeNodeComponent("compliance5"),
    qualification9: makeNodeComponent("qualification9"),
    administration10: makeNodeComponent("administration10"),
    administration11: makeNodeComponent("administration11"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "About Real Asset Registry",
      description:
        "The Real Assets Registry serves as the backbone of the Real Assets Ecosystem",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAbout;
/* prettier-ignore-end */
