/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jKoNqQf9yT8Pn9RBFtbwnS
// Component: jOtoE5Owp6JQ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Linkedin from "../../Linkedin"; // plasmic-import: GxrDkYHCty2n/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectcss
import sty from "./PlasmicTeamPages.module.css"; // plasmic-import: jOtoE5Owp6JQ/css

createPlasmicElementProxy;

export type PlasmicTeamPages__VariantMembers = {};
export type PlasmicTeamPages__VariantsArgs = {};
type VariantPropType = keyof PlasmicTeamPages__VariantsArgs;
export const PlasmicTeamPages__VariantProps = new Array<VariantPropType>();

export type PlasmicTeamPages__ArgsType = {};
type ArgPropType = keyof PlasmicTeamPages__ArgsType;
export const PlasmicTeamPages__ArgProps = new Array<ArgPropType>();

export type PlasmicTeamPages__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  freeBox?: Flex__<"div">;
  httpsWwwLinkedinComInPetaMilanSheHerB4307A27?: Flex__<"a"> &
    Partial<LinkProps>;
  linkedin?: Flex__<typeof Linkedin>;
};

export interface DefaultTeamPagesProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTeamPages__RenderFunc(props: {
  variants: PlasmicTeamPages__VariantsArgs;
  args: PlasmicTeamPages__ArgsType;
  overrides: PlasmicTeamPages__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"175px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"175px"}
        loading={"lazy"}
        src={{
          src: "/plasmic/realassets_foundation_homepage/images/image5.webp",
          fullWidth: 736,
          fullHeight: 552,
          aspectRatio: undefined
        }}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___9A9Kj
          )}
        >
          {"Peta Milan"}
        </div>
        <PlasmicLink__
          data-plasmic-name={"httpsWwwLinkedinComInPetaMilanSheHerB4307A27"}
          data-plasmic-override={
            overrides.httpsWwwLinkedinComInPetaMilanSheHerB4307A27
          }
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.httpsWwwLinkedinComInPetaMilanSheHerB4307A27
          )}
          component={Link}
          platform={"nextjs"}
        >
          <Linkedin
            data-plasmic-name={"linkedin"}
            data-plasmic-override={overrides.linkedin}
            className={classNames("__wab_instance", sty.linkedin)}
          />
        </PlasmicLink__>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__sv0Af
        )}
      >
        {
          "Regenerative Investments Specialist. Principal Henmil Group Family Office"
        }
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "img",
    "freeBox",
    "httpsWwwLinkedinComInPetaMilanSheHerB4307A27",
    "linkedin"
  ],
  img: ["img"],
  freeBox: [
    "freeBox",
    "httpsWwwLinkedinComInPetaMilanSheHerB4307A27",
    "linkedin"
  ],
  httpsWwwLinkedinComInPetaMilanSheHerB4307A27: [
    "httpsWwwLinkedinComInPetaMilanSheHerB4307A27",
    "linkedin"
  ],
  linkedin: ["linkedin"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  freeBox: "div";
  httpsWwwLinkedinComInPetaMilanSheHerB4307A27: "a";
  linkedin: typeof Linkedin;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTeamPages__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTeamPages__VariantsArgs;
    args?: PlasmicTeamPages__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTeamPages__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTeamPages__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTeamPages__ArgProps,
          internalVariantPropNames: PlasmicTeamPages__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTeamPages__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTeamPages";
  } else {
    func.displayName = `PlasmicTeamPages.${nodeName}`;
  }
  return func;
}

export const PlasmicTeamPages = Object.assign(
  // Top-level PlasmicTeamPages renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    freeBox: makeNodeComponent("freeBox"),
    httpsWwwLinkedinComInPetaMilanSheHerB4307A27: makeNodeComponent(
      "httpsWwwLinkedinComInPetaMilanSheHerB4307A27"
    ),
    linkedin: makeNodeComponent("linkedin"),

    // Metadata about props expected for PlasmicTeamPages
    internalVariantProps: PlasmicTeamPages__VariantProps,
    internalArgProps: PlasmicTeamPages__ArgProps
  }
);

export default PlasmicTeamPages;
/* prettier-ignore-end */
