/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jKoNqQf9yT8Pn9RBFtbwnS
// Component: 02LfOPXrtXh3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeaderNav from "../../HeaderNav"; // plasmic-import: my-sNiLoLdMm/component
import RealAssetHomepageButton from "../../RealAssetHomepageButton"; // plasmic-import: 2sMJd1XUninS/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import ButtonRaf from "../../ButtonRaf"; // plasmic-import: CiitqlwcWvJo/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import { TeamMemberCard } from "../../TeamMemberCard"; // plasmic-import: d2bq7OWtrjwt/codeComponent
import Footer from "../../Footer"; // plasmic-import: 53qTPHRQ24MF/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jKoNqQf9yT8Pn9RBFtbwnS/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 02LfOPXrtXh3/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: RrJ-jCDXQg3b/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: KHCF_T-muDuf/icon
import LinkedinSvgrepoComSvgIcon from "./icons/PlasmicIcon__LinkedinSvgrepoComSvg"; // plasmic-import: ZZu2QufwXikE/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  homePage?: Flex__<"div">;
  headerNav?: Flex__<typeof HeaderNav>;
  realAssetHomepageButton?: Flex__<typeof RealAssetHomepageButton>;
  foreground2?: Flex__<"div">;
  aboutRafStack?: Flex__<"div">;
  aboutRafText?: Flex__<"div">;
  h1?: Flex__<"h1">;
  embedHtml?: Flex__<typeof Embed>;
  purposeGroundingValue?: Flex__<"div">;
  aboutRaf?: Flex__<"div">;
  aboutRaf2?: Flex__<"div">;
  scales?: Flex__<"svg">;
  realGoldIntro?: Flex__<"div">;
  introRg?: Flex__<"div">;
  buttonRaf?: Flex__<typeof ButtonRaf>;
  initialFocusAndCoreServices?: Flex__<"div">;
  purposeGroundingValue2?: Flex__<"div">;
  qualification2?: Flex__<"div">;
  administration?: Flex__<"div">;
  compliance?: Flex__<"div">;
  sliderCarousel?: Flex__<typeof SliderWrapper>;
  qualification?: Flex__<"div">;
  administration2?: Flex__<"div">;
  complianceMobile?: Flex__<"div">;
  baselines?: Flex__<"div">;
  purposeGroundingValue3?: Flex__<"div">;
  realAssetRegistry?: Flex__<"div">;
  purposeGroundingValue4?: Flex__<"div">;
  purposeGroundingValue5?: Flex__<"div">;
  aboutRaf5?: Flex__<"div">;
  ourBoardOfAdvisors?: Flex__<"div">;
  ourBoardOfAdvisors2?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"homePage"}
          data-plasmic-override={overrides.homePage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.homePage
          )}
        >
          <HeaderNav
            data-plasmic-name={"headerNav"}
            data-plasmic-override={overrides.headerNav}
            className={classNames("__wab_instance", sty.headerNav)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__rxfgD)}>
            <div className={classNames(projectcss.all, sty.freeBox__l4S7M)}>
              <RealAssetHomepageButton
                data-plasmic-name={"realAssetHomepageButton"}
                data-plasmic-override={overrides.realAssetHomepageButton}
                className={classNames(
                  "__wab_instance",
                  sty.realAssetHomepageButton
                )}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__vHyhQ)}
                displayHeight={"40px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"40px"}
                src={{
                  src: "/plasmic/realassets_foundation_homepage/images/untitledDesign12Png.png",
                  fullWidth: 500,
                  fullHeight: 500,
                  aspectRatio: undefined
                }}
              />

              <div className={classNames(projectcss.all, sty.freeBox__etOTy)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___6Dk5N
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  {"Home"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__hlzE4
                  )}
                  component={Link}
                  href={`/about`}
                  platform={"nextjs"}
                >
                  {"About"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__omzrm
                  )}
                  component={Link}
                  href={`/team`}
                  platform={"nextjs"}
                >
                  {"Team"}
                </PlasmicLink__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___7CF8F)}>
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__vZu5K)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6OoXs
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "The foundation behind a new asset class\u2014built for a new system-compliance & regeneration at its core. "
                    : "The foundation behind a new asset class\u2014built for a new system- with compliance & regeneration at its core. "}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zxW3W
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {
                          "The Real Assets Foundation (RAF) upholds the integrity of real property assets\u2014from in-ground resources to regenerative land trusts."
                        }
                      </span>
                    </React.Fragment>
                  ) : (
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {
                          "The Real Assets Foundation (RAF) upholds the integrity of real property assets\u2014"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {
                          "from in-ground resources to regenerative land trusts."
                        }
                      </span>
                    </React.Fragment>
                  )}
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"aboutRafStack"}
            data-plasmic-override={overrides.aboutRafStack}
            className={classNames(projectcss.all, sty.aboutRafStack)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___77LIb)}>
              <div className={classNames(projectcss.all, sty.freeBox___9MAs)}>
                <div
                  data-plasmic-name={"aboutRafText"}
                  data-plasmic-override={overrides.aboutRafText}
                  className={classNames(projectcss.all, sty.aboutRafText)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {"About RAF"}
                      </span>
                    </React.Fragment>
                  </h1>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rjpnj)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uSNl)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tssD8
                        )}
                      >
                        {
                          "The Real Assets Foundation (RAF) is the administrative trustee and compliance oversight for a new class of real\u2011estate assets, starting with in\u2011ground gold. RAF is responsible for maintaining the highest standards of integrity as it relates to the unitization of real property assets. The Real Assets Foundation verifies geological assays, sets regenerative baselines, verifies compliance, and manages the Real Assets Registry.\n\n enables trusts to meet legal, ecological, and social obligations for investor credibility. Our job is simple: ground integrity in place, so value may move\u2014ethically, transparently, and with public trust.\nReal Assets Foundation: where regulatory precision and planetary renewal find common ground."
                        }
                      </div>
                    </div>
                    <Embed
                      data-plasmic-name={"embedHtml"}
                      data-plasmic-override={overrides.embedHtml}
                      className={classNames("__wab_instance", sty.embedHtml)}
                      code={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? '<style>\r\n@keyframes spin {\r\n  from {\r\n    transform: rotate(0deg);\r\n  }\r\n  to {\r\n    transform: rotate(360deg);\r\n  }\r\n}\r\n\r\n.spinning-logo-container {\r\n  width: 100%;\r\n  max-width: 7rem; /* 112px - same as w-28 */\r\n  height: 7rem;\r\n  margin: 0 auto 2rem auto;\r\n  animation: spin 120s linear infinite;\r\n}\r\n\r\n.spinning-logo-container img {\r\n  width: 100%;\r\n  height: 100%;\r\n  object-fit: contain;\r\n}\r\n</style>\r\n\r\n<div class="spinning-logo-container">\r\n  <img src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/692f134d3bb9758c337278ae/339b29b1a_realassetslogoimage.png" alt="Real Assets Foundation Logo">\r\n</div>'
                          : '<style>\r\n@keyframes spin {\r\n  from {\r\n    transform: rotate(0deg);\r\n  }\r\n  to {\r\n    transform: rotate(360deg);\r\n  }\r\n}\r\n\r\n.spinning-logo {\r\n  animation: spin 120s linear infinite;\r\n}\r\n</style>\r\n\r\n<div class="w-28 h-28 mx-auto mb-8 spinning-logo">\r\n  <img src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/692f134d3bb9758c337278ae/339b29b1a_realassetslogoimage.png" alt="Real Assets Foundation Logo" class="w-full h-full object-contain">\r\n</div>'
                      }
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__cvVqY)}>
            <div className={classNames(projectcss.all, sty.freeBox__xUxWt)}>
              <div
                data-plasmic-name={"purposeGroundingValue"}
                data-plasmic-override={overrides.purposeGroundingValue}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.purposeGroundingValue
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Purpose - "}
                  </span>
                  <React.Fragment>{"\n"}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Grounding Value"}
                  </span>
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__tJlXe)}>
                <div className={classNames(projectcss.all, sty.freeBox__b3Yz4)}>
                  <CircleIcon
                    className={classNames(projectcss.all, sty.svg___0Lnv)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qSzj
                    )}
                  >
                    {"About RAF"}
                  </div>
                  <CircleIcon
                    className={classNames(projectcss.all, sty.svg__qAKr6)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"aboutRaf"}
                    data-plasmic-override={overrides.aboutRaf}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.aboutRaf
                    )}
                  >
                    {"RealGold"}
                  </div>
                  <CircleIcon
                    className={classNames(projectcss.all, sty.svg___0Qd0L)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"aboutRaf2"}
                    data-plasmic-override={overrides.aboutRaf2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.aboutRaf2
                    )}
                  >
                    {"Registry"}
                  </div>
                  <CircleIcon
                    className={classNames(projectcss.all, sty.svg__ux9Qp)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Q40R
                  )}
                >
                  {
                    "The Real Assets Foundation (RAF) is the administrative trustee and compliance authority for a new class of real-estate\u2013based assets\u2014beginning with in-ground gold (RealGold). \n\nThrough its integrated framework of legal, ecological, and technological oversight, RAF enables lawful participation in real assets that regenerate rather than deplete.\n\nWe maintain neutral, auditable trust structures that register and administer real estate-based assets such as minerals, timber rights, water rights, community infrastructure, carbon credits, biodiversity units, and more. "
                  }
                </div>
              </div>
              <Icon2Icon
                data-plasmic-name={"scales"}
                data-plasmic-override={overrides.scales}
                className={classNames(projectcss.all, sty.scales)}
                role={"img"}
              />
            </div>
          </div>
          <div
            data-plasmic-name={"realGoldIntro"}
            data-plasmic-override={overrides.realGoldIntro}
            className={classNames(projectcss.all, sty.realGoldIntro)}
          >
            <div
              data-plasmic-name={"introRg"}
              data-plasmic-override={overrides.introRg}
              className={classNames(projectcss.all, sty.introRg)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__g57WT)}>
                <div className={classNames(projectcss.all, sty.freeBox__vu1Oe)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ihs20)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__xh3Ph)}
                      displayHeight={"297px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "none"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "339px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/realassets_foundation_homepage/images/image2.jpg",
                        fullWidth: 640,
                        fullHeight: 960,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__rc6Oj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__traF
                        )}
                      >
                        {
                          "The Real Assets Foundation grounds the formal trust layer for assets held in Tripartite Trusts (Mineral, Biological, Social Estates). It interfaces with landholders, trustees, and capital channels to ensure, lawful, neutral, auditable integrity, and fiduciary responsibility. \nThe main two purposes are:\nBridging the value of place-bound assets to markets\nConfirming compliance and eligibility for release of ongoing funds intended for common benefit (rather than personal gain)"
                        }
                      </div>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__kWwcz
                        )}
                        component={Link}
                        href={"https://real.gold"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <ButtonRaf
                          data-plasmic-name={"buttonRaf"}
                          data-plasmic-override={overrides.buttonRaf}
                          className={classNames(
                            "__wab_instance",
                            sty.buttonRaf
                          )}
                        >
                          {"Check out RealGold"}
                        </ButtonRaf>
                      </PlasmicLink__>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"initialFocusAndCoreServices"}
            data-plasmic-override={overrides.initialFocusAndCoreServices}
            className={classNames(
              projectcss.all,
              sty.initialFocusAndCoreServices
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__w8YfI)}>
              <div
                data-plasmic-name={"purposeGroundingValue2"}
                data-plasmic-override={overrides.purposeGroundingValue2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.purposeGroundingValue2
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Initial Focus"}
                  </span>
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kvAsF)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___67VUh
                  )}
                >
                  {
                    "Operating and maintaining the integrity of assets and ownership in the Real Asset Registry"
                  }
                </div>
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8SZvu
              )}
            >
              {"Core Services"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__bGgWp)}>
              <div
                data-plasmic-name={"qualification2"}
                data-plasmic-override={overrides.qualification2}
                className={classNames(projectcss.all, sty.qualification2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox___7ZrL)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vOmxH
                    )}
                  >
                    {"Qualification"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9AHd
                  )}
                >
                  {
                    "Verifies geological, ecological, and governance baselines before assets enter the Real Assets Registry. Ensures projects meet standards for lawful ownership, non-extraction, and stewardship continuity."
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"administration"}
                data-plasmic-override={overrides.administration}
                className={classNames(projectcss.all, sty.administration)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__qCdbl)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5HkUy
                    )}
                  >
                    {"Administration"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hn2Jd
                  )}
                >
                  {
                    "Acts as trustee for Delaware Statutory Trusts (DSTs) tied to real property assets. Manages the Real Assets Registry, maintains title records, and oversees controlled release schedules.\n"
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"compliance"}
                data-plasmic-override={overrides.compliance}
                className={classNames(projectcss.all, sty.compliance)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ukDLn)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xw9YS
                    )}
                  >
                    {"Compliance"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___86NU
                  )}
                >
                  {
                    "Aligns all activity with SEC/IRS frameworks and regenerative commitments. Provides the fiduciary infrastructure that allows lawful trade of unitized, non-extractive assets."
                  }
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__bNe7E)}>
              {(() => {
                const child$Props = {
                  arrowColor: true ? "var(--antd-colorWarning)" : undefined,
                  autoplay: true,
                  beforeChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "currentSlide",
                      ["sliderCarousel", "currentSlide"],
                      SliderWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  className: classNames("__wab_instance", sty.sliderCarousel),
                  dots: false,
                  initialSlide: generateStateValueProp($state, [
                    "sliderCarousel",
                    "currentSlide"
                  ]),
                  ref: ref => {
                    $refs["sliderCarousel"] = ref;
                  },
                  sliderScopeClassName: sty["sliderCarousel__slider"],
                  slidesPerRow: 1
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "currentSlide",
                      plasmicStateName: "sliderCarousel.currentSlide"
                    }
                  ],
                  [],
                  SliderWrapper_Helpers ?? {},
                  child$Props
                );

                return (
                  <SliderWrapper
                    data-plasmic-name={"sliderCarousel"}
                    data-plasmic-override={overrides.sliderCarousel}
                    {...child$Props}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <div
                        data-plasmic-name={"qualification"}
                        data-plasmic-override={overrides.qualification}
                        className={classNames(
                          projectcss.all,
                          sty.qualification
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zXl5G
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gUfGt
                            )}
                          >
                            {"Qualification"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__saovD
                          )}
                        >
                          {
                            "Verifies geological, ecological, and governance baselines before assets enter the Real Assets Registry. Ensures projects meet standards for lawful ownership, non-extraction, and stewardship continuity."
                          }
                        </div>
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <div
                        data-plasmic-name={"administration2"}
                        data-plasmic-override={overrides.administration2}
                        className={classNames(
                          projectcss.all,
                          sty.administration2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pUzT
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jfyUp
                            )}
                          >
                            {"Administration"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vUpeE
                          )}
                        >
                          {
                            "Acts as trustee for Delaware Statutory Trusts (DSTs) tied to real property assets. Manages the Real Assets Registry, maintains title records, and oversees controlled release schedules.\n"
                          }
                        </div>
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <div
                        data-plasmic-name={"complianceMobile"}
                        data-plasmic-override={overrides.complianceMobile}
                        className={classNames(
                          projectcss.all,
                          sty.complianceMobile
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zpb1F
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qip6Y
                            )}
                          >
                            {"Compliance"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wknr5
                          )}
                        >
                          {
                            "Aligns all activity with SEC/IRS frameworks and regenerative commitments. Provides the fiduciary infrastructure that allows lawful trade of unitized, non-extractive assets."
                          }
                        </div>
                      </div>
                    ) : null}
                  </SliderWrapper>
                );
              })()}
            </div>
            <div
              data-plasmic-name={"baselines"}
              data-plasmic-override={overrides.baselines}
              className={classNames(projectcss.all, sty.baselines)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___91Wm8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zDeyI
                  )}
                >
                  {
                    "The Foundation invites a plurality of regenerative logics, from geological stewardship to traditional ecological knowledge (TEK), grounding them in a shared layer of accountability, transparency and trust."
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"purposeGroundingValue3"}
                data-plasmic-override={overrides.purposeGroundingValue3}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.purposeGroundingValue3
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Baselines and Vetting"}
                  </span>
                </React.Fragment>
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__b3YJo)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "71px"
                    : "121px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "101px"
                    : "auto"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/realassets_foundation_homepage/images/image3.png",
                  fullWidth: 576,
                  fullHeight: 576,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <div
            data-plasmic-name={"realAssetRegistry"}
            data-plasmic-override={overrides.realAssetRegistry}
            className={classNames(projectcss.all, sty.realAssetRegistry)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__jBjIp)}>
              <div className={classNames(projectcss.all, sty.freeBox__uTbNc)}>
                <div className={classNames(projectcss.all, sty.freeBox__lDnTe)}>
                  <div
                    data-plasmic-name={"purposeGroundingValue4"}
                    data-plasmic-override={overrides.purposeGroundingValue4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.purposeGroundingValue4
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {"Real Asset Registry"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    data-plasmic-name={"purposeGroundingValue5"}
                    data-plasmic-override={overrides.purposeGroundingValue5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.purposeGroundingValue5
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {"        "}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gdyql)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__owjBi)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bdngV
                        )}
                      >
                        {"Monitors Stewardship"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hw40W
                        )}
                      >
                        {
                          "Tracks regenerative performance and ties asset release to ecological outcomes."
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zvNk9
                        )}
                      >
                        {"Resisters and Unitizes Assets"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lLsUj
                        )}
                      >
                        {
                          "Converts mineral rights into compliant, tradable real-estate units."
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__aolLy
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__f5IoD
                          )}
                        >
                          {"Facilitates Market Access"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zJ8X
                          )}
                        >
                          {
                            "Enables lawful trade under 1031 exchange and DST structures."
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"aboutRaf5"}
                      data-plasmic-override={overrides.aboutRaf5}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.aboutRaf5
                      )}
                    >
                      {"Real Asset Registry"}
                    </div>
                  </div>
                </div>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rf8Yu)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "165px"
                      : "393px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "524px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/realassets_foundation_homepage/images/_0E4A53Eb12B77Ecd3D37Da0Fd2F81626Jpg.jpg",
                    fullWidth: 564,
                    fullHeight: 796,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___11M3D)}>
            <div
              data-plasmic-name={"ourBoardOfAdvisors"}
              data-plasmic-override={overrides.ourBoardOfAdvisors}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.ourBoardOfAdvisors
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"Board of Directors"}
                </span>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.columns__d49C1)}>
              <div className={classNames(projectcss.all, sty.column__hnsL)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__fI04T
                  )}
                  displayStyle={"modal"}
                  email={"ferananda@real.gold"}
                  fullBio={
                    "<p><strong>Ferananda Ibarra</strong>, Director of the Commons Engine, is a visionary social innovator and regenerative entrepreneur, bringing over fifteen years of experience with community building and currency design. Her background in collective intelligence, integral theories, and deep wealth design inform her creativity and facilitation of systems and organizations that can address our global challenges.</p>\n<p>She is specifically interested in &lsquo;building the commons&rsquo; as a way of incentivizing new patterns of collaboration, coordination, value generation and the embodiment of the principles of nature. Ferananda believes that nature shows us the most powerful keys to wholeness.</p>\n<p>She works with Holo and Holochain in the space of distributed applications, decentralization, distributed ledger systems, and crypto-economies. Holo finished a successful Initial Community Offering (ethical ICO) and is creating a Distributed App and hosting Ecosystem.</p>"
                  }
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/_1746575659001Jpeg.jpg"
                  }
                  linkedIn={"https://www.linkedin.com/in/ferananda/"}
                  name={"Ferananda Ibarra"}
                  shortBio={
                    "Short bio Designing Societal Systems for Interdependence. Financial and economies that serve life, bioregional work & community aliveness (culture).goes here"
                  }
                  title={"Secretary"}
                  twitter={""}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hgX1Q)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__dmNHn
                  )}
                  displayStyle={"modal"}
                  email={"ishan@real.gold"}
                  fullBio={
                    "<p><strong>Arthur Brock</strong> builds targeted currencies which shape the social dynamics of our emerging post-industrial economy. He has created more than a hundred designs for multi-currency systems, and his software company has built and deployed dozens of those systems. His designs include currencies for: collaborative scientific research, sustainable fishery management, corporate compensation plans, employee stock options, community-based economic development, business barter and exchange, triple-bottom-line trade credits, open source software development, customer loyalty programs, water rights, recirculating gift certificates, community service, employee performance management, arts &amp; culture development, efficient resource sharing &amp; management, and community &amp; environmental impact assessment. He is currently launching Holochain, an alternative to blockchain for running fully P2P distributed applications.</p>"
                  }
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/headshot2Jpg.jpg"
                  }
                  linkedIn={"https://www.linkedin.com/in/ferananda/"}
                  name={"Arthur Brock"}
                  shortBio={
                    "A systems architect and technology innovator with more than two decades of experience building decentralized economic systems."
                  }
                  title={"President"}
                  twitter={"https://www.linkedin.com/in/1shan/"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___22IBa)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__s7KRa
                  )}
                  displayStyle={"modal"}
                  email={"ishan@real.gold"}
                  fullBio={"<p>Full bio goes here</p>"}
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/_1759773825168Jpeg.jpg"
                  }
                  linkedIn={"https://www.linkedin.com/in/1shan/"}
                  name={"Ishan Shapiro"}
                  shortBio={
                    "An innovative creative director with over 15 years of experience spearheading groundbreaking immersive storytelling and experience design for a wide range of global brands"
                  }
                  title={"Chief Financial Officer"}
                  twitter={""}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__adzn6)}>
            <div
              data-plasmic-name={"ourBoardOfAdvisors2"}
              data-plasmic-override={overrides.ourBoardOfAdvisors2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.ourBoardOfAdvisors2
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"Advisory Committee"}
                </span>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.columns__aiTl)}>
              <div className={classNames(projectcss.all, sty.column__gvu6R)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__gh7Xg
                  )}
                  displayStyle={"modal"}
                  email={``}
                  fullBio={
                    "<p>Peta Milan is a visionary systems resource and practitioner of regenerative investing. As the Principal of Henmil Group Family Office, &nbsp;she channels capital into ventures and places that enliven ecological vitality, cultural integrity, economic viability and social thriving in service of long-term resilience. Rather than treating value as a single metric, Peta works to elevate the quality of relationships within living systems&mdash;human and non-human alike&mdash;and applies this lens to the design of assets, portfolios, funds, and places. Her career bridges international governance, climate, capital and finance and security policy, and advanced studies in competitive and blockchain strategy, experiences that revealed the limits of problem-solution thinking and informed a deeper approach: capital as a force that can enliven entire life systems.</p>"
                  }
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/image5.webp"
                  }
                  linkedIn={
                    "https://www.linkedin.com/in/peta-milan-she-her-b4307a27/"
                  }
                  name={"Peta Milan"}
                  shortBio={``}
                  title={
                    "Regenerative Investments Specialist | Principal Henmil Group Family Office"
                  }
                  twitter={""}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__st2A6)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__vmTAn
                  )}
                  displayStyle={"modal"}
                  email={``}
                  fullBio={
                    "<p>Courtney is a strategist and financial innovator bridging institutional markets with the emerging regenerative economy. With a background spanning structured products, private equity, and fund design, she has guided the evolution of financial systems toward greater transparency, liquidity, and impact. Her expertise in market architecture and regulatory pathways helps ground visionary ideas in executable frameworks, paving the way for precedent-setting financial models that honor both investors and the Earth.</p>"
                  }
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/courneyMurthaJpeg.jpg"
                  }
                  linkedIn={
                    "https://www.linkedin.com/in/courtney-murtha-012a052b/"
                  }
                  name={"Courtney Murtha"}
                  shortBio={``}
                  title={"Institutional Strategy | Financial Design"}
                  twitter={""}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__vr1K)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__oOseh
                  )}
                  displayStyle={"modal"}
                  email={``}
                  fullBio={
                    "<p>Helen Holden is a legal strategist and transformational systems guide known for catalyzing New York State&rsquo;s ban on fracking&mdash;a landmark legal shift recognized by the Goldman Environmental Prize. Trained in law but operating beyond its conventional boundaries, Helen brings deep insight into how legal, social, and financial systems unconsciously replicate domination-based patterns, even under the banner of reform. Her work now focuses on guiding institutions and individuals sensing the limits of conventional change toward deeper, dimensional shifts in how power, sovereignty, and value are structured. As an advisor to the Real Assets Foundation, Helen brings a rare ability to perceive where legacy systems subtly contradict regenerative intent&mdash;and to engage with dimensional compressions that formality alone cannot detect.</p>"
                  }
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/helenSlottjeJpeg.jpg"
                  }
                  linkedIn={
                    "https://www.linkedin.com/in/courtney-murtha-012a052b/"
                  }
                  name={"Helen Holden"}
                  shortBio={``}
                  title={
                    "Legal Strategist | Catalyst of New York\u2019s statewide ban on fracking"
                  }
                  twitter={"https://www.linkedin.com/in/helenslottje/"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__hl6X9)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__eIJz
                  )}
                  displayStyle={"modal"}
                  email={``}
                  fullBio={
                    "<div>Kate Bennett is a systems innovator reimagining how capital flows can serve life by default, not exception. As Co-Founder &amp; CEO of Adaluma Tech, she is building real-time infrastructure that integrates verified non-financial data into financial workflows, embedding trusted sustainability signals into institutional decision-making and making capital accountable to the outcomes that matter.</div>\n<div>&nbsp;</div>\n<div>Her PhD research in Regenerative Finance explores regenerative approaches to finance, governance, and impact, and examines the role of advanced technologies in transforming capital flows for development across emerging and developing markets. With over a decade working inside the mining sector, Kate brings firsthand experience in community engagement, human rights, and on-site operations. Her deep awareness of the systemic challenges within legacy industries informs her work to shift extractive paradigms toward regenerative ones.</div>"
                  }
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/kateBennettJpeg.jpg"
                  }
                  linkedIn={
                    "https://www.linkedin.com/in/courtney-murtha-012a052b/"
                  }
                  name={"Kate Bennett"}
                  shortBio={``}
                  title={"Fintech Infrastructure | PHD Regenerative Finance"}
                  twitter={"https://www.linkedin.com/in/ktlbennett/"}
                />
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns___9YeDy)}>
              <div className={classNames(projectcss.all, sty.column__t3Yvg)}>
                <TeamMemberCard
                  className={classNames(
                    "__wab_instance",
                    sty.teamMemberCard__xVFcA
                  )}
                  displayStyle={"modal"}
                  email={``}
                  fullBio={
                    "<p>As a social impact entrepreneur, Lee has a portfolio of business and non-profit interests to channel his diverse interests and skills. Lee operates an Adventure Therapy program for BC&rsquo;s youth custody centre and has for over 20 years. An extensive early career guiding wilderness programs as contemporary rites of passage shaped his orientation. Land-based experiences for sovereign self authenticity. As an artist and poet, Lee collaborates with a creative and diverse network of artists, athletes, and wordsmiths to disrupt the snow sports industry. Poet Snow Sports started as a creative outlet and art project into a storytelling platform for creative expression and authentic experiences. Lee&rsquo;s a co-founder of ChinookX Technologies, a team of Indigenous and non-Indigenous social innovators focused on regional economic development and climate solutions. Lee is an advocate for reconciliation and ally in the assertion of Indigenous sovereignty. These passions started with his prior involvement in post-apartheid South Africa as part of Nelson Mandela's Reconstruction and Development Programme and as advisor to the Inter-Ministerial Committee on Restorative Justice. Lee is also a published author of the philosophy nonfiction book &lsquo;Rapt in Awe.&rsquo;</p>"
                  }
                  imageUrl={
                    "/plasmic/realassets_foundation_homepage/images/leeWhite937X1024Jpg.jpg"
                  }
                  linkedIn={
                    "https://www.linkedin.com/in/lee-white-live-in-flow/"
                  }
                  name={"Lee White"}
                  shortBio={``}
                  title={
                    "Social impact entrepreneur + artist, athlete, writer + sovereign data, sovereign self innovator"
                  }
                  twitter={""}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__sy3P)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kyBhc)}
                  displayHeight={"194px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/realassets_foundation_homepage/images/courneyMurthaJpeg.jpg",
                    fullWidth: 200,
                    fullHeight: 200,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7JiY
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h4
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4__pcun8
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "var(--token-HIt_SMre_dXW)" }}
                          >
                            {"Courtney Murtha"}
                          </span>
                        </React.Fragment>
                      </h4>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3CqNv
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__m8Btq
                        )}
                      >
                        {
                          "Strategist and financial innovator bridging institutional markets with the emerging regenerative economy."
                        }
                      </h6>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__siMsW
                  )}
                  component={Link}
                  href={"https://www.linkedin.com/in/courtney-murtha-012a052b/"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <LinkedinSvgrepoComSvgIcon
                    className={classNames(projectcss.all, sty.svg___52Hh1)}
                    role={"img"}
                  />
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.column___0ZbA)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__w9Noe)}
                  displayHeight={"202px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/realassets_foundation_homepage/images/hhsReducedSizeHeadshotJpeg.jpg",
                    fullWidth: 432,
                    fullHeight: 455,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__txycu
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h4
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4__fe4U4
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "var(--token-HIt_SMre_dXW)" }}
                          >
                            {"Helen Holden Slottje"}
                          </span>
                        </React.Fragment>
                      </h4>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zsxCo
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__oB6Nm
                        )}
                      >
                        {
                          "Legal strategist and transformational systems, brings deep insight into legal, social, and financial systems."
                        }
                      </h6>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__cuEre
                  )}
                  component={Link}
                  href={"https://www.linkedin.com/in/helenslottje/"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__bRw9V
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <LinkedinSvgrepoComSvgIcon
                      className={classNames(projectcss.all, sty.svg__sLdqF)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.column___017Cu)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__oIm4)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/realassets_foundation_homepage/images/kateBennettJpeg.jpg",
                    fullWidth: 200,
                    fullHeight: 200,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i5K8
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h4
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4___9C5Ul
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#E5E7EB" }}
                          >
                            {"Kate Bennett"}
                          </span>
                        </React.Fragment>
                      </h4>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mr5Fg
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__mAmx8
                        )}
                      >
                        {
                          "Systems innovator reimagining how capital flows can serve life by default, not exception."
                        }
                      </h6>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__gk08
                  )}
                  component={Link}
                  href={"https://www.linkedin.com/in/ktlbennett/"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <LinkedinSvgrepoComSvgIcon
                    className={classNames(projectcss.all, sty.svg___4ACi7)}
                    role={"img"}
                  />
                </PlasmicLink__>
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  homePage: [
    "homePage",
    "headerNav",
    "realAssetHomepageButton",
    "foreground2",
    "aboutRafStack",
    "aboutRafText",
    "h1",
    "embedHtml",
    "purposeGroundingValue",
    "aboutRaf",
    "aboutRaf2",
    "scales",
    "realGoldIntro",
    "introRg",
    "buttonRaf",
    "initialFocusAndCoreServices",
    "purposeGroundingValue2",
    "qualification2",
    "administration",
    "compliance",
    "sliderCarousel",
    "qualification",
    "administration2",
    "complianceMobile",
    "baselines",
    "purposeGroundingValue3",
    "realAssetRegistry",
    "purposeGroundingValue4",
    "purposeGroundingValue5",
    "aboutRaf5",
    "ourBoardOfAdvisors",
    "ourBoardOfAdvisors2",
    "footer"
  ],
  headerNav: ["headerNav"],
  realAssetHomepageButton: ["realAssetHomepageButton"],
  foreground2: ["foreground2"],
  aboutRafStack: ["aboutRafStack", "aboutRafText", "h1", "embedHtml"],
  aboutRafText: ["aboutRafText", "h1", "embedHtml"],
  h1: ["h1"],
  embedHtml: ["embedHtml"],
  purposeGroundingValue: ["purposeGroundingValue"],
  aboutRaf: ["aboutRaf"],
  aboutRaf2: ["aboutRaf2"],
  scales: ["scales"],
  realGoldIntro: ["realGoldIntro", "introRg", "buttonRaf"],
  introRg: ["introRg", "buttonRaf"],
  buttonRaf: ["buttonRaf"],
  initialFocusAndCoreServices: [
    "initialFocusAndCoreServices",
    "purposeGroundingValue2",
    "qualification2",
    "administration",
    "compliance",
    "sliderCarousel",
    "qualification",
    "administration2",
    "complianceMobile",
    "baselines",
    "purposeGroundingValue3"
  ],
  purposeGroundingValue2: ["purposeGroundingValue2"],
  qualification2: ["qualification2"],
  administration: ["administration"],
  compliance: ["compliance"],
  sliderCarousel: [
    "sliderCarousel",
    "qualification",
    "administration2",
    "complianceMobile"
  ],
  qualification: ["qualification"],
  administration2: ["administration2"],
  complianceMobile: ["complianceMobile"],
  baselines: ["baselines", "purposeGroundingValue3"],
  purposeGroundingValue3: ["purposeGroundingValue3"],
  realAssetRegistry: [
    "realAssetRegistry",
    "purposeGroundingValue4",
    "purposeGroundingValue5",
    "aboutRaf5"
  ],
  purposeGroundingValue4: ["purposeGroundingValue4"],
  purposeGroundingValue5: ["purposeGroundingValue5"],
  aboutRaf5: ["aboutRaf5"],
  ourBoardOfAdvisors: ["ourBoardOfAdvisors"],
  ourBoardOfAdvisors2: ["ourBoardOfAdvisors2"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  homePage: "div";
  headerNav: typeof HeaderNav;
  realAssetHomepageButton: typeof RealAssetHomepageButton;
  foreground2: "div";
  aboutRafStack: "div";
  aboutRafText: "div";
  h1: "h1";
  embedHtml: typeof Embed;
  purposeGroundingValue: "div";
  aboutRaf: "div";
  aboutRaf2: "div";
  scales: "svg";
  realGoldIntro: "div";
  introRg: "div";
  buttonRaf: typeof ButtonRaf;
  initialFocusAndCoreServices: "div";
  purposeGroundingValue2: "div";
  qualification2: "div";
  administration: "div";
  compliance: "div";
  sliderCarousel: typeof SliderWrapper;
  qualification: "div";
  administration2: "div";
  complianceMobile: "div";
  baselines: "div";
  purposeGroundingValue3: "div";
  realAssetRegistry: "div";
  purposeGroundingValue4: "div";
  purposeGroundingValue5: "div";
  aboutRaf5: "div";
  ourBoardOfAdvisors: "div";
  ourBoardOfAdvisors2: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "homePage") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("homePage"),
  {
    // Helper components rendering sub-elements
    headerNav: makeNodeComponent("headerNav"),
    realAssetHomepageButton: makeNodeComponent("realAssetHomepageButton"),
    foreground2: makeNodeComponent("foreground2"),
    aboutRafStack: makeNodeComponent("aboutRafStack"),
    aboutRafText: makeNodeComponent("aboutRafText"),
    h1: makeNodeComponent("h1"),
    embedHtml: makeNodeComponent("embedHtml"),
    purposeGroundingValue: makeNodeComponent("purposeGroundingValue"),
    aboutRaf: makeNodeComponent("aboutRaf"),
    aboutRaf2: makeNodeComponent("aboutRaf2"),
    scales: makeNodeComponent("scales"),
    realGoldIntro: makeNodeComponent("realGoldIntro"),
    introRg: makeNodeComponent("introRg"),
    buttonRaf: makeNodeComponent("buttonRaf"),
    initialFocusAndCoreServices: makeNodeComponent(
      "initialFocusAndCoreServices"
    ),
    purposeGroundingValue2: makeNodeComponent("purposeGroundingValue2"),
    qualification2: makeNodeComponent("qualification2"),
    administration: makeNodeComponent("administration"),
    compliance: makeNodeComponent("compliance"),
    sliderCarousel: makeNodeComponent("sliderCarousel"),
    qualification: makeNodeComponent("qualification"),
    administration2: makeNodeComponent("administration2"),
    complianceMobile: makeNodeComponent("complianceMobile"),
    baselines: makeNodeComponent("baselines"),
    purposeGroundingValue3: makeNodeComponent("purposeGroundingValue3"),
    realAssetRegistry: makeNodeComponent("realAssetRegistry"),
    purposeGroundingValue4: makeNodeComponent("purposeGroundingValue4"),
    purposeGroundingValue5: makeNodeComponent("purposeGroundingValue5"),
    aboutRaf5: makeNodeComponent("aboutRaf5"),
    ourBoardOfAdvisors: makeNodeComponent("ourBoardOfAdvisors"),
    ourBoardOfAdvisors2: makeNodeComponent("ourBoardOfAdvisors2"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Real Assets Foundation - Homepage",
      description:
        "The foundation behind a new asset class—built for a new system- with compliance & regeneration at its core. ",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
